"""Add salary management tables

Revision ID: 77c05dfd8044
Revises: 66b04cec7033
Create Date: 2026-04-18 22:45:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "77c05dfd8044"
down_revision = "66b04cec7033"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "salaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("professional_id", sa.Integer(), nullable=False),
        sa.Column("base_salary", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("salary_type", sa.String(length=20), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["professionals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payrolls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payroll_period", sa.String(length=7), nullable=False),
        sa.Column("professional_id", sa.Integer(), nullable=False),
        sa.Column("salary_id", sa.Integer(), nullable=False),
        sa.Column("base_salary", sa.Float(), nullable=False),
        sa.Column("total_allowances", sa.Float(), nullable=True),
        sa.Column("total_deductions", sa.Float(), nullable=True),
        sa.Column("gross_salary", sa.Float(), nullable=False),
        sa.Column("net_salary", sa.Float(), nullable=False),
        sa.Column("working_days", sa.Integer(), nullable=True),
        sa.Column("actual_days_worked", sa.Integer(), nullable=True),
        sa.Column("overtime_hours", sa.Float(), nullable=True),
        sa.Column("overtime_rate", sa.Float(), nullable=True),
        sa.Column("overtime_amount", sa.Float(), nullable=True),
        sa.Column("tax_amount", sa.Float(), nullable=True),
        sa.Column("social_insurance", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("processed_date", sa.DateTime(), nullable=True),
        sa.Column("payment_date", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["professionals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["salary_id"],
            ["salaries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salary_components",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("salary_id", sa.Integer(), nullable=False),
        sa.Column("component_type", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("percentage", sa.Float(), nullable=True),
        sa.Column("is_taxable", sa.Boolean(), nullable=True),
        sa.Column("is_fixed", sa.Boolean(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["salary_id"],
            ["salaries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salary_payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payroll_id", sa.Integer(), nullable=False),
        sa.Column("professional_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("payment_method", sa.String(length=20), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("reference_number", sa.String(length=100), nullable=True),
        sa.Column("bank_name", sa.String(length=100), nullable=True),
        sa.Column("account_number", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("transaction_id", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("processed_by", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["payroll_id"],
            ["payrolls.id"],
        ),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["professionals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("salary_payments")
    op.drop_table("salary_components")
    op.drop_table("payrolls")
    op.drop_table("salaries")
    # ### end Alembic commands ###
