"""add commission and debt fields to salary and payroll

Revision ID: f776b321806b
Revises: a9f23b1c4d77
Create Date: 2026-04-26 00:21:52.069891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f776b321806b'
down_revision = 'a9f23b1c4d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_commission', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('debt_deductions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('deducted_expense_ids', sa.Text(), nullable=True))

    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission_percentage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.drop_column('commission_percentage')

    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.drop_column('deducted_expense_ids')
        batch_op.drop_column('debt_deductions')
        batch_op.drop_column('total_commission')

    # ### end Alembic commands ###
