"""add dental_chart to patients

Revision ID: fdf4ae02df0d
Revises: f776b321806b
Create Date: 2026-05-01 02:08:22.951963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf4ae02df0d'
down_revision = 'f776b321806b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dental_chart', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('dental_chart')

    # ### end Alembic commands ###
